version: '2'
services:
    jhipsterapplicationexemple1-app:
        image: jhipsterapplicationexemple1
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipsterapplicationexemple1-mysql:3306/jhipsterapplicationexemple1?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8090:8090
    jhipsterapplicationexemple1-mysql:
        extends:
            file: mysql.yml
            service: jhipsterapplicationexemple1-mysql
